package api

import (
	"crypto/subtle"
	"fmt"
	"io/fs"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"sync"

	"github.com/erishen/cicdkit/internal/config"
	"github.com/erishen/cicdkit/internal/kb"
	"github.com/erishen/cicdkit/internal/llm"
	"github.com/erishen/cicdkit/internal/pipeline"
	"github.com/erishen/cicdkit/internal/store"
)

// BuildStamp 是后端构建时间戳，由 main 在启动时写入（每次发版/修复手动升一位）。
// 前端 footer 会把它和前端 UI_BUILD 一起展示，用于一眼确认浏览器连的是不是最新后端
// 二进制——排查「改了代码却没生效」这类问题时，比对这个戳比猜进程是否重启过更可靠。
var BuildStamp = "dev"

// Server wires the HTTP API and embedded static assets to the store + runner.
type Server struct {
	cfg     *config.Config
	store   store.Store
	runner  *pipeline.Runner
	mux     *http.ServeMux
	llm     *llm.Config
	llmPath string
	kb      *kb.KB
	kbPath  string
	kbMu    sync.Mutex
	webFS   fs.FS
	// autoToken is the one-time token generated by AUTO_TOKEN (empty otherwise).
	// It is the ONLY token we ever inject into the served UI; an explicitly
	// configured API_TOKEN is never exposed to the page.
	autoToken string
}

// New constructs the server. webFS is the (sub) filesystem rooted at the web
// assets directory. autoToken is the generated one-time token when AUTO_TOKEN
// is enabled ("" otherwise). It also loads the optional LLM config so the AI
// diagnosis feature is ready without a restart after the operator saves
// settings.
func New(cfg *config.Config, st store.Store, runner *pipeline.Runner, webFS fs.FS, autoToken string) *Server {
	llmPath := filepath.Join(cfg.DataDir, "llm.json")
	llmCfg, _ := llm.Load(llmPath)
	kbPath := filepath.Join(cfg.DataDir, "kb.json")
	kbCfg := kb.Load(kbPath)
	if llmCfg != nil {
		if llmCfg.Enabled {
			log.Printf("LLM 诊断: 已启用 (base_url=%s model=%s key_set=%v)", llmCfg.BaseURL, llmCfg.Model, llmCfg.APIKey != "")
		} else {
			log.Printf("LLM 诊断: 未启用 (enabled=false; base_url=%q model=%q key_set=%v) — 在「⚙ 设置」启用并保存后生效", llmCfg.BaseURL, llmCfg.Model, llmCfg.APIKey != "")
		}
	}
	s := &Server{cfg: cfg, store: st, runner: runner, mux: http.NewServeMux(), llm: llmCfg, llmPath: llmPath, kb: kbCfg, kbPath: kbPath, webFS: webFS, autoToken: autoToken}
	s.routes(webFS)
	return s
}

// Handler returns the root http.Handler with authentication applied. A global
// request-body cap (10 MiB) guards against oversized payloads — the only body
// endpoints here are JSON config/diagnose calls, so this never bites legitimate
// traffic but caps a malicious one.
func (s *Server) Handler() http.Handler {
	return http.MaxBytesHandler(s.withAuth(s.mux), 10<<20)
}

// withAuth guards /api/* with the configured API token. Static assets stay open
// so the UI can load and then supply the token itself; /api/health stays open
// for probes, and the webhook keeps its own secret check.
func (s *Server) withAuth(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		token := s.cfg.Server.APIToken
		if token == "" || !strings.HasPrefix(r.URL.Path, "/api/") {
			next.ServeHTTP(w, r)
			return
		}
		if r.URL.Path == "/api/health" || r.URL.Path == "/api/version" {
			next.ServeHTTP(w, r)
			return
		}
		// The webhook may opt out of the API token: when WebhookSecret is set the
		// handler enforces that secret itself, so it keeps its own auth. But when
		// no secret is configured we must NOT leave it wide open — fall through to
		// the normal API_TOKEN check so an exposed server (non-loopback) cannot be
		// triggered by anyone who merely knows a project id.
		if strings.HasPrefix(r.URL.Path, "/api/webhook/") && s.cfg.Server.WebhookSecret != "" {
			next.ServeHTTP(w, r)
			return
		}
		if !tokenMatches(r, token) {
			writeError(w, http.StatusUnauthorized,
				"未授权：请通过 Authorization: Bearer <token> 或 X-API-Token 提供 API Token")
			return
		}
		next.ServeHTTP(w, r)
	})
}

// tokenMatches compares the presented credential in constant time.
func tokenMatches(r *http.Request, want string) bool {
	got := r.Header.Get("X-API-Token")
	if got == "" {
		if a := r.Header.Get("Authorization"); strings.HasPrefix(a, "Bearer ") {
			got = strings.TrimPrefix(a, "Bearer ")
		}
	}
	if got == "" {
		return false
	}
	return subtle.ConstantTimeCompare([]byte(got), []byte(want)) == 1
}

func (s *Server) routes(webFS fs.FS) {
	s.mux.HandleFunc("/api/health", s.handleHealth)
	s.mux.HandleFunc("/api/version", s.handleVersion)
	s.mux.HandleFunc("/api/projects", s.methodSwitch(map[string]http.HandlerFunc{
		http.MethodGet:  s.handleListProjects,
		http.MethodPost: s.handleCreateProject,
	}))
	s.mux.HandleFunc("/api/projects/scan", s.handleScanProject)
	s.mux.HandleFunc("/api/fs/roots", s.handleFSRoots)
	s.mux.HandleFunc("/api/fs/list", s.handleFSList)
	s.mux.HandleFunc("/api/projects/", s.handleProjectByID)
	s.mux.HandleFunc("/api/runs", s.methodSwitch(map[string]http.HandlerFunc{
		http.MethodGet:    s.handleListRuns,
		http.MethodDelete: s.handleClearRuns,
	}))
	s.mux.HandleFunc("/api/runs/", s.handleRunByID)
	s.mux.HandleFunc("/api/deployments", s.methodSwitch(map[string]http.HandlerFunc{
		http.MethodGet:    s.handleListDeployments,
		http.MethodDelete: s.handleClearDeployments,
	}))
	s.mux.HandleFunc("/api/deployments/", s.handleDeploymentByID)
	s.mux.HandleFunc("/api/config/llm", s.methodSwitch(map[string]http.HandlerFunc{
		http.MethodGet:  s.handleConfigLLM,
		http.MethodPut:  s.handleConfigLLM,
	}))
	s.mux.HandleFunc("/api/config/llm/test", s.handleTestLLM)
	// 暴露全局 SSH 连接默认值（来自 .env 的 CICD_SSH_*），供前端「一键导入腾讯云
	// 目标」使用——避免在 UI 里硬编码这些值。受 API Token 保护（同其他 /api/*）。
	s.mux.HandleFunc("/api/config/ssh-defaults", s.handleConfigSSHDefaults)
	s.mux.HandleFunc("/api/kb", s.handleKBList)
	s.mux.HandleFunc("/api/kb/", s.handleKBItem)
	s.mux.HandleFunc("/api/webhook/", s.handleWebhook)
	s.mux.Handle("/", s.serveApp())
}

// handleConfigSSHDefaults returns the global SSH connection defaults sourced
// from the CICD_SSH_* env vars (.env). The frontend uses this to offer a
// one-click "import Tencent Cloud target" action instead of hard-coding the
// host/port/user/key in the UI. It is token-protected like every other
// /api/* route when an API Token is configured.
func (s *Server) handleConfigSSHDefaults(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet {
		writeError(w, http.StatusMethodNotAllowed, "方法不被允许")
		return
	}
	envOr := func(k, d string) string {
		if v := strings.TrimSpace(os.Getenv(k)); v != "" {
			return v
		}
		return d
	}
	writeJSON(w, http.StatusOK, map[string]string{
		"host":            envOr("CICD_SSH_HOST", ""),
		"user":            envOr("CICD_SSH_USER", ""),
		"port":            envOr("CICD_SSH_PORT", ""),
		"key_path":        envOr("CICD_SSH_KEY_PATH", ""),
		"build_platforms": envOr("CICD_SSH_BUILD_PLATFORMS", ""),
		"label":           "腾讯云（来自 .env CICD_SSH_*）",
	})
}

func (s *Server) methodSwitch(m map[string]http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if h, ok := m[r.Method]; ok {
			h(w, r)
			return
		}
		writeError(w, http.StatusMethodNotAllowed, "方法不被允许")
	}
}

// serveApp serves the embedded single-page UI. Real static assets (files that
// exist in the embedded FS, e.g. JS/CSS bundles) are served directly with
// correct content types; everything else (the root path and unknown
// client-side routes) falls back to index.html. When AUTO_TOKEN generated a
// one-time token, it is injected into the page so the local browser
// authenticates transparently — the token is fixed for the process lifetime.
func (s *Server) serveApp() http.Handler {
	fileServer := http.FileServer(http.FS(s.webFS))
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		path := r.URL.Path
		if path != "/" {
			// If the requested path maps to a real embedded file, serve it.
			if f, err := s.getFile(path); err == nil {
				f.Close()
				fileServer.ServeHTTP(w, r)
				return
			}
		}
		// Root or unknown route: serve (injected) index.html as SPA fallback.
		s.serveIndex(w, r)
	})
}

// getFile opens name relative to the embedded web FS (leading slash stripped).
func (s *Server) getFile(name string) (fs.File, error) {
	return s.webFS.Open(strings.TrimPrefix(name, "/"))
}

// serveIndex reads the embedded index.html and, when AUTO_TOKEN is active,
// injects the one-time token into a global the front-end picks up automatically.
func (s *Server) serveIndex(w http.ResponseWriter, r *http.Request) {
	data, err := fs.ReadFile(s.webFS, "index.html")
	if err != nil {
		http.Error(w, "UI 资源缺失", http.StatusInternalServerError)
		return
	}
	if s.autoToken != "" {
		inject := fmt.Sprintf("<script>window.__CICD_API_TOKEN__=%q;</script>", s.autoToken)
		html := string(data)
		if i := strings.Index(html, "</head>"); i >= 0 {
			html = html[:i] + inject + html[i:]
		} else if i := strings.Index(html, "</body>"); i >= 0 {
			html = html[:i] + inject + html[i:]
		} else {
			html = inject + html
		}
		data = []byte(html)
	}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.Write(data)
}

func writeJSON(w http.ResponseWriter, code int, v interface{}) {
	w.Header().Set("Content-Type", "application/json; charset=utf-8")
	w.WriteHeader(code)
	_ = encodeJSON(w, v)
}

func writeError(w http.ResponseWriter, code int, msg string) {
	writeJSON(w, code, map[string]string{"error": msg})
}

// encodeJSON is a tiny wrapper so we can keep json usage in one place.
func encodeJSON(w http.ResponseWriter, v interface{}) error {
	return jsonEncoder(w).Encode(v)
}
